name: docker-image
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker build -t my-docker-image:latest -f 03-app-dotnet/Dockerfile 03-app-dotnet/
            - name: Run the Docker container    
              run: docker run -d -p 80:80 my-docker-image:latest
            - name: Wait and verify service
              run: |
                sleep 2
                curl http://localhost:80
           
